In [1]:
import numpy as np
import pandas as pd

### Declaring a vector in NumPy

In [2]:
ar = [1, 2, 3, 4, 5]
numpy_ar = np.array(ar)
print(numpy_ar)

[1 2 3 4 5]


### Arithmetic with 2 Arrays in NumPy

In [3]:

'''
This will result in concantenation
'''
# ar_1 = [1, 2, 3, 4, 5]
# ar_2 = [5, 4, 3, 2, 1]


'''
This will result in addition
'''
ar_1 = np.array([1, 2, 3, 4, 5])
ar_2 = np.array([5, 4, 3, 2, 1])



ar_3 = ar_1 + ar_2
print(ar_3)

[6 6 6 6 6]


### Matrix Operations in NumPy

In [49]:
matrix = [[1, 10], [11, 1]] #The basic identity matrix
np_matrix = np.asarray(matrix)





print(np_matrix.shape)
print(np_matrix[:, 1])

(2, 2)
[10  1]


#### Inverse of a matrix

In [50]:
inv_matrix = np.linalg.inv(matrix)
print(inv_matrix)

[[-0.00917431  0.09174312]
 [ 0.10091743 -0.00917431]]


#### Eigenvalues

In [51]:
# np.linalg.eigvalsh(np_matrix) # This must only be used when we know for a fact that the matrix is symmetric
# The algorithm that eigh uses is called the "Jacobi eigenvalue algorithm". 
# This algorithm is based on the fact that the eigenvalues of a symmetric matrix can be found by solving a system of linear equations.
np.linalg.eigvals(np_matrix)

array([11.48808848, -9.48808848])

#### Matrix multiplication

In [52]:
mat_1 = np.array([[1, 2], [3, 4]])
mat_2 = np.array([[0, 1], [1, 0]])
mat_1^mat_2

array([[1, 3],
       [2, 4]])

### Statistics

#### Mean

In [57]:
ar_1 = np.array([-2, -1, 0, 1, 2])
print("Mean: ", ar_1.mean())
print("Standard Deviation: ", ar_1.std())
print("Variance: ", ar_1.var())

Mean:  0.0
Standard Deviation:  1.4142135623730951
Variance:  2.0
